# Generated by Django 3.2.3 on 2023-03-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
